events {
    worker_connections 1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;
    
    client_max_body_size 30M;
    
    # เปิด CORS ให้ Frontend และ Backend ใช้งานได้
    add_header Access-Control-Allow-Origin http://ai-garden.it.kmitl.ac.th always;
    add_header Access-Control-Allow-Credentials true always;
    add_header Access-Control-Allow-Methods "GET, POST, OPTIONS, DELETE, PUT";
    add_header Access-Control-Allow-Headers "Authorization, Content-Type, Accept";

    server {
        listen 80;
        server_name localhost;

        client_max_body_size 50M;

        location / {
            root /usr/share/nginx/html;
            index index.html;
            try_files $uri $uri/ /index.html;
        }

        location /public/ {
            root /usr/share/nginx/html;
            autoindex on;
        }


        # Proxy ไปยัง Backend NestJS ที่รันบน Port 3000
        location /api/ {
            rewrite /api/(.*) /$1  break;
            proxy_pass http://ai-garden-system-nest-backend-1:3000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header Cookie $http_cookie;
            proxy_cookie_path / "/; Secure; HttpOnly; SameSite=None";
        }

        location /models/suture {
            rewrite /models/suture/(.*) /$1  break;
            proxy_pass http://segment-segment-tools-service-1:4000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }



        # กำหนด MIME Type ให้ถูกต้องสำหรับ JavaScript และ CSS
#        location ~* \.js$ {
#            root /usr/share/nginx/html;
#            types { application/javascript js; }
#            add_header Content-Type application/javascript;
#        }
#
#        location ~* \.css$ {
#            root /usr/share/nginx/html;
#            types { text/css css; }
#            add_header Content-Type text/css;
#        }
        
        # ตั้งค่าการแคชไฟล์ static เพื่อลดการโหลดซ้ำ
#        location ~ /\. {
#            deny all;
#        }
    }
}
