version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: ai_garden_db
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  backend:
    build:
      context: .
    restart: always
    ports:
      - "3000:3000" # เปิดพอร์ตสำหรับ Backend
    volumes:
      - ./uploads:/app/uploads # Map โฟลเดอร์ Local ไปยัง Docker Container
    environment:
      DATABASE_URL: postgres://postgres:admin@db:5432/ai_garden_db # ตั้งค่าเชื่อมต่อกับ Postgres
      NODE_ENV: development

volumes:
  db-data: # สำหรับ Postgres Database