# nest-backend
FROM node:18 AS builder
WORKDIR /app


COPY package*.json ./
RUN npm install --omit=dev


COPY . .
RUN npm run build


FROM node:18-alpine AS production
WORKDIR /app

COPY --from=builder /app/dist ./dist
COPY --from=builder /app/package*.json ./
COPY --from=builder /app/node_modules ./node_modules


EXPOSE 3000

# รัน Backend
CMD ["node", "dist/main.js"]
