events {
    worker_connections 1024;  # จำนวนการเชื่อมต่อที่สามารถจัดการได้พร้อมกัน
}


http {
    upstream backend {
        server nest-backend:3000; # ชื่อของ service nest-backend ใน docker-compose
    }

    upstream frontend {
        server react-frontend:5173;  # เปลี่ยนให้ตรงกับพอร์ตของ React frontend
    }

    server {
        listen 80;

        # สำหรับ Backend (NestJS)
        location /api/ {
            proxy_pass http://backend; # เชื่อมต่อกับ NestJS
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # สำหรับ Frontend (React)
        location / {
            proxy_pass http://frontend; # เชื่อมต่อกับ React frontend
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}